### ISSUE TITLE
  ERROR: Failed building wheel for grpcio-tools   Running setup.py clean for grpcio-tools Failed to build grpcio-tools ERROR: Could not build wheels for grpcio-tools, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by TheBestOfTheQuests** [bigscience-workshop/petals#401] opened 2023-07-21 16:46 UTC
I tried installing petals via pip on wsl kali linux on a virtual enviroment, but it throws an error when trying to install grpcio-tools. When installing the package seperately, it works, but when installing petals it doesnt. I cant submit the whole log because it is too long, but heres the relevant part:
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for grpcio-tools
  Running setup.py clean for grpcio-tools
Failed to build grpcio-tools
ERROR: Could not build wheels for grpcio-tools, which is required to install pyproject.toml-based projects

**Comment by r-fumachi** [comment] 2023-07-21 22:49
duplicate of https://github.com/bigscience-workshop/petals/issues/388 ? Python 3.11 isn't supported atm

**Comment by borzunov** [comment] 2023-07-22 14:30
Python 3.11 support was fixed in #393. Please update your server and try again:

`pip install git+https://github.com/bigscience-workshop/petals`

Let us know if you have any other issues!

**Closed by borzunov** 2023-07-22 14:30 UTC
